### ISSUE TITLE
This is sick but...

### ISSUE THREAD

**Issue by SandmansDreams** [shsethi/obsidian-rollover-weekly-todos#1]
Would be awesome if it also had the function to do this with daily notes as I don't use weekly notes, and most of the transfers would happen on the day-to-day.
This is just a suggestion.

**Comment by shsethi** [comment]
Hey @SandmansDreams, for day-to-day rollover you can use another plugin [obsidian-rollover-daily-todos](https://github.dev/lumoe/obsidian-rollover-daily-todos/tree/master), which was inspiration for this plugin.

**Comment by SandmansDreams** [comment]
> Hey @SandmansDreams, for day-to-day rollover you can use another plugin [obsidian-rollover-daily-todos](https://github.dev/lumoe/obsidian-rollover-daily-todos/tree/master), which was inspiration for this plugin.

Oh awesome! Thank you.
